version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend-app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/frontend-app"
    schedule:
      interval: "monthly"