version: '3.8'
services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/testworks
    command: ["sleep", "infinity"]
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data:
