version: '3.8'
services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"


volumes:
  postgres_data:
