name: Snyk Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: |
          cd frontend
          npm install

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          poetry install

      # Setup Snyk CLI
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Snyk Code test (SAST) for Node.js
      - name: Snyk Code test for Node.js
        run: snyk code test --sarif > snyk-node-code.sarif

      # Snyk Open Source test (SCA) for Node.js
      - name: Snyk Open Source test for Node.js
        run: snyk test --all-projects

      # Snyk Code test (SAST) for Python
      - name: Snyk Code test for Python
        run: snyk code test --sarif > snyk-python-code.sarif

      # Snyk Open Source test (SCA) for Python
      - name: Snyk Open Source test for Python
        run: snyk test --all-projects

      # Upload result to GitHub Code Scanning for Node.js
      - name: Upload Node.js result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-node-code.sarif

      # Upload result to GitHub Code Scanning for Python
      - name: Upload Python result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-python-code.sarif
