name: Snyk Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Node.js dependencies
        run: |
          cd frontend
          npm install

      - name: Snyk scan for Node.js project
        run: snyk test --all-projects
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          WORKING_DIRECTORY: frontend

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Python dependencies
        run: |
          cd backend
          poetry install

      - name: Snyk scan for Python project
        run: snyk test --all-projects
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          WORKING_DIRECTORY: backend

      - name: Upload Snyk results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'snyk.sarif'
